universe: ["SPY", "QQQ", "AAPL", "MSFT", "NVDA", "TSLA"]
paths:
  data_dir: "artifacts/local_data"
  features_dir: "artifacts/features"
  results_dir: "artifacts/results"
risk:
  per_trade_dollar: 25
  max_open_risk: 200
  max_daily_loss_pct: 0.75
  max_positions: 4
  risk_dollars_per_trade: 25
  max_gross_exposure: 0.6   # 60% of equity
  daily_loss_limit_pct: 2.0
execution:
  mode: paper     # 'paper' now, 'live' later
  slippage_bps: 2
  fee_per_trade: 0.5
backtest:
  start: "2022-01-01"
  end: "2025-08-31"
  fee_bps: 1.0
  slippage_bps: 3.0
sentiment:
  enable: false
  sic_threshold: 0.0
  decay_lambda: 0.05
labels:
  enable_triple_barrier: false
  up_sigma: 2.0
  down_sigma: 1.2
  time_bar_days: 10
features:
  rsi_period: 14
  atr_period: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  vwap_window: 20
  vol_mean_window: 20
portfolio:  
  enable_hrp: false
  vol_target_annual: 0.15
strategy:
  rsi_cross_level: 25.0
  vol_mult_min: 1.2
  macd_hist_floor: 0.0
  atr_sizing_multiple: 1.2
  sweep:
    lookback_bars: 5              # allow sub-signals to align within last K bars
    require_same_bar: false       # if true, all conditions must hold on same bar
    require_macd_rising: true     # if false, drop “rising” check; keep > floor
    price_slack_bps: 2.0          # Close >= VWAP * (1 - slack_bps/1e4)
    entry_edge_lookback: 3        # window for “new signal” edge in entries
